name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Starting up RabbitMQ
      run: docker compose up -d

    - name: Setup Scala using Coursier
      uses: coursier/setup-action@v1
      with:
        apps: sbt

    - name: Cache Coursier dependencies
      uses: coursier/cache-action@v6

    - name: Tests
      run: sbt -J-Xms4G -J-Xmx4G buildFs2Rabbit

    - name: Shutting down RabbitMQ
      run: docker compose down

    - name: Binary incompatibilities check
      run: sbt -J-Xms4G -J-Xmx4G +mimaReportBinaryIssues
