jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Scala using Coursier
        uses: coursier/setup-action@v1
        with:
          apps: sbt

      - uses: olafurpg/setup-gpg@v3
      - env:
          PGP_PASSPHRASE: "${{ secrets.PGP_PASSPHRASE }}"
          PGP_SECRET: "${{ secrets.PGP_SECRET }}"
          SONATYPE_PASSWORD: "${{ secrets.SONATYPE_PASSWORD }}"
          SONATYPE_USERNAME: "${{ secrets.SONATYPE_USERNAME }}"
        name: "Publish ${{ github.ref }}"
        run: sbt ci-release

name: Release
on:
  push:
    branches:
      - master
    tags:
      - "*"
