name: scalafmt
on:
  - push

jobs:
  scalafmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: scalafmt-native-action
        uses: jrouly/scalafmt-native-action@v4